#!/usr/bin/perl
my $STRNG = $ARGV[0];
my $lengte = length $STRNG;
print "$STRNG lengte $lengte \n";
sub writepasswd {
        my $filename = 'pwreport';
        my $mode = 0600;   
        chmod $mode, $filename;
	my $datum=localtime();
        open(my $fh, '>>', $filename) or die;
        print $fh localtime()." My first report generated by perl\n";
        close $fh;
        my $mode = 0000;   
        chmod $mode, $filename;
        print "done\n";
}
writepasswd;
